target("LibEvent1")
    set_kind("binary")
    add_files("main1.cpp")
    add_links("event")
target_end()

target("LibEvent2")
    set_kind("binary")
    add_files("main2.cpp")
    add_links("event")
target_end()

target("LibEvent3-Server")
    set_kind("binary")
    add_files("main3_server.cpp")
    add_links("event")
target_end()

add_requires("gtest")

target("LibEvent3-Client")
    set_kind("binary")
    add_files("main3_client.cpp")
    add_packages("gtest")
target_end()
